# Generated by Django 5.2.4 on 2025-09-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='moviedirector',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director'),
        ),
        migrations.AddField(
            model_name='moviedirector',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(through='movies.MovieDirector', to='movies.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='movies.movietag', verbose_name='Теги'),
        ),
        migrations.AlterUniqueTogether(
            name='moviedirector',
            unique_together={('movie', 'director')},
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-time_created'], name='movies_movi_time_cr_663284_idx'),
        ),
    ]
